import { readFileSync, writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import { ggBridgeTypescriptSideVersion } from '../src/gg_bridge_typescript_side_version';

// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
//
// Repairs the version literal in
// src/gg_bridge_typescript_side_version.ts
// when it drifts from package.json. Drift is not an error here: the literal
// is rewritten and the test passes.

describe('gg_bridge_typescript_side_version.ts', () => {
  it('matches the version in package.json', () => {
    const manifest = JSON.parse(
      readFileSync('package.json', 'utf8'),
    ) as { version?: string };
    expect(manifest.version).toBeTruthy();

    const declaration = 'export const ggBridgeTypescriptSideVersion = ';
    const expected = `${declaration}'${manifest.version}';`;
    const path = 'src/gg_bridge_typescript_side_version.ts';

    if (!readFileSync(path, 'utf8').includes(expected)) {
      writeFileSync(
        path,
        readFileSync(path, 'utf8').replace(
          new RegExp(`${declaration}'[^']*';`),
          expected,
        ),
      );
    }

    expect(readFileSync(path, 'utf8')).toContain(expected);
    expect(ggBridgeTypescriptSideVersion).toBeTruthy();
  });
});
