// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/gg_bridge_typescript_side_version.test.ts.

/** The version of the `@tssuite/gg-bridge-typescript-side` package. */
export const ggBridgeTypescriptSideVersion = '0.0.3';
